#!/bin/sh

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

PATTERN='^[a-z]+ : [a-z가-힣\- ]+$'

if ! echo "$commit_msg" | awk "/$PATTERN/" > /dev/null; then
  echo "커밋 양식을 지켜주세요'"
  exit 1
fi

echo "커밋 메시지가 패턴에 맞습니다"
